{
 "title": "Dispatcher",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "WorkerStatus",
    "query": {
     "query": "label_values(dispatcher_workers,Status)"
    }
   },
   {
    "name": "Project",
    "query": {
     "query": "label_values(dispatcher_tasks,Project)"
    }
   },
   {
    "name": "Department",
    "query": {
     "query": "label_values(dispatcher_tasks,Department)"
    }
   },
   {
    "name": "TaskUser",
    "query": {
     "query": "label_values(dispatcher_tasks,User)"
    }
   },
   {
    "name": "TechVar",
    "query": {
     "query": "label_values(chunk_global_rendertime,techvar)"
    }
   },
   {
    "name": "WorkerEnable",
    "query": {
     "query": "label_values(dispatcher_workers,Enable)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Statuses by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "dispatcher_workers{Status=~\"$WorkerStatus\",Enable=~\"$WorkerEnable\"}",
     "legendFormat": "{{Name}}"
    },
    {
     "expr": "count(dispatcher_workers{Status=~\"$WorkerStatus\",Enable=~\"$WorkerEnable\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job statuses",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dispatcher_jobs) by (Status)",
     "legendFormat": "{{job_status}}"
    },
    {
     "expr": "chunk_global_rendertime:job_statuses_total",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Tasks  statuses",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(Status) (count by (JobName, Status, Project, Department) (dispatcher_tasks))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Jobs by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (User) (dispatcher_jobs)",
     "legendFormat": "{{User}}"
    }
   ]
  },
  {
   "title": "Tasks not completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dispatcher_tasks:not_completed:per_project",
     "legendFormat": "{{Project}}"
    },
    {
     "expr": "sum(dispatcher_tasks:not_completed:per_project)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Instances statuses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dispatcher_workers) by (Status)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Jobs statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(dispatcher_jobs) by (Status)",
     "legendFormat": "{{Status}}"
    },
    {
     "expr": "count(logs{eventDescription=~\".*timed.*\"}) by (exported_job,project)",
     "legendFormat": "{{project}}_{{exported_job}}"
    }
   ]
  },
  {
   "title": "Render time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Task Render Time per Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dispatcher_tasks:rendertime:average:per_job > 0",
     "legendFormat": "{{Project}}_{{JobName}}"
    }
   ]
  },
  {
   "title": "Average Render time per worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dispatcher_tasks:rendertime:average:per_worker > 0",
     "legendFormat": "{{Worker}}"
    }
   ]
  },
  {
   "title": "Max Render time per job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "dispatcher_tasks:rendertime:max:per_job > 0",
     "legendFormat": "{{Project}}_{{JobName}}"
    }
   ]
  }
 ]
}