{
 "title": "Dispatcher statistics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Job amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct(date_trunc('hour', j.submitted)) AS date_jour,\n(\n    SELECT COUNT(*)\n    FROM jobs\n    WHERE date_trunc('hour', submitted) < date_trunc('hour', j.submitted)\n) AS sum_jobs\nFROM jobs j\nORDER BY date_trunc('hour', j.submitted)"
    }
   ]
  },
  {
   "title": "Job amount per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('hour', j.submitted) AS time,\n(\n    SELECT COUNT(*)\n    FROM jobs\n    WHERE date_trunc('hour', submitted) < date_trunc('hour', j.submitted)\n    AND project = j.project\n) AS sum_jobs,\nj.project\nFROM jobs j\nGROUP BY j.project, j.submitted\nORDER BY time"
    }
   ]
  },
  {
   "title": "Time spent per project",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  project,\n  sum(time_spent) AS timespent\nFROM\n  jobs\nGROUP BY\n  project\nORDER BY\n  timespent"
    }
   ]
  },
  {
   "title": "Jobs per project",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*),\n  project\nFROM\n  jobs\nGROUP BY\n  project"
    }
   ]
  },
  {
   "title": "Submitted jobs per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as submitted_jobs,\n  date_trunc('day', submitted)\nFROM\n  jobs\nGROUP BY\n  date_trunc('day', submitted)"
    }
   ]
  },
  {
   "title": "Submitted jobs per user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', submitted) as time,\n  COUNT(*),\n  \"user\"\nFROM\n  jobs\nGROUP BY\n  time,\n  \"user\"\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Submitted jobs per project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', submitted) as time,\n  COUNT(*),\n  \"project\"\nFROM\n  jobs\nGROUP BY\n  time,\n  \"project\"\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Submitted jobs per department",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', submitted) as time,\n  COUNT(*),\n  \"department\"\nFROM\n  jobs\nGROUP BY\n  time,\n  \"department\"\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Submitted jobs per department & project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', submitted) as time,\n  COUNT(*),\n  department,\n  project\nFROM\n  jobs\nGROUP BY\n  time,\n  department,\n  project\nORDER BY\n  time\n"
    }
   ]
  }
 ]
}