package deadline

import "time"

var Job_Status = map[int]string{
	0: "Unknown",
	1: "Active",
	2: "Suspended",
	3: "Completed",
	4: "Failed",
	6: "Pending",
}

type Jobs []struct {
	Props struct {
		Name                 string    `json:"Name"`
		Batch                string    `json:"Batch"`
		User                 string    `json:"User"`
		Region               string    `json:"Region"`
		Cmmt                 string    `json:"Cmmt"`
		Dept                 string    `json:"Dept"`
		Frames               string    `json:"Frames"`
		Chunk                int       `json:"Chunk"`
		Tasks                int       `json:"Tasks"`
		Grp                  string    `json:"Grp"`
		Pool                 string    `json:"Pool"`
		SecPool              string    `json:"SecPool"`
		Pri                  int       `json:"Pri"`
		ReqAss               []any     `json:"ReqAss"`
		ScrDep               []any     `json:"ScrDep"`
		Conc                 int       `json:"Conc"`
		ConcLimt             bool      `json:"ConcLimt"`
		AuxSync              bool      `json:"AuxSync"`
		Int                  bool      `json:"Int"`
		IntPer               int       `json:"IntPer"`
		RemTmT               int       `json:"RemTmT"`
		Seq                  bool      `json:"Seq"`
		Reload               bool      `json:"Reload"`
		NoEvnt               bool      `json:"NoEvnt"`
		OnComp               int       `json:"OnComp"`
		Protect              bool      `json:"Protect"`
		PathMap              []any     `json:"PathMap"`
		AutoTime             bool      `json:"AutoTime"`
		TimeScrpt            bool      `json:"TimeScrpt"`
		MinTime              int       `json:"MinTime"`
		MaxTime              int       `json:"MaxTime"`
		Timeout              int       `json:"Timeout"`
		FrameTimeout         bool      `json:"FrameTimeout"`
		StartTime            int       `json:"StartTime"`
		InitializePluginTime int       `json:"InitializePluginTime"`
		Dep                  []any     `json:"Dep"`
		DepFrame             bool      `json:"DepFrame"`
		DepFrameStart        int       `json:"DepFrameStart"`
		DepFrameEnd          int       `json:"DepFrameEnd"`
		DepComp              bool      `json:"DepComp"`
		DepDel               bool      `json:"DepDel"`
		DepFail              bool      `json:"DepFail"`
		DepPer               float64   `json:"DepPer"`
		NoBad                bool      `json:"NoBad"`
		OverAutoClean        bool      `json:"OverAutoClean"`
		OverClean            bool      `json:"OverClean"`
		OverCleanDays        int       `json:"OverCleanDays"`
		OverCleanType        int       `json:"OverCleanType"`
		JobFailOvr           bool      `json:"JobFailOvr"`
		JobFailErr           int       `json:"JobFailErr"`
		TskFailOvr           bool      `json:"TskFailOvr"`
		TskFailErr           int       `json:"TskFailErr"`
		SndWarn              bool      `json:"SndWarn"`
		NotOvr               bool      `json:"NotOvr"`
		SndEmail             bool      `json:"SndEmail"`
		SndPopup             bool      `json:"SndPopup"`
		NotEmail             []any     `json:"NotEmail"`
		NotUser              []string  `json:"NotUser"`
		NotNote              string    `json:"NotNote"`
		Limits               []any     `json:"Limits"`
		ListedSlaves         []any     `json:"ListedSlaves"`
		White                bool      `json:"White"`
		MachLmt              int       `json:"MachLmt"`
		MachLmtProg          float64   `json:"MachLmtProg"`
		PrJobScrp            string    `json:"PrJobScrp"`
		PoJobScrp            string    `json:"PoJobScrp"`
		PrTskScrp            string    `json:"PrTskScrp"`
		PoTskScrp            string    `json:"PoTskScrp"`
		Schd                 int       `json:"Schd"`
		SchdDays             int       `json:"SchdDays"`
		SchdDate             time.Time `json:"SchdDate"`
		SchdStop             time.Time `json:"SchdStop"`
		MonStart             string    `json:"MonStart"`
		MonStop              string    `json:"MonStop"`
		TueStart             string    `json:"TueStart"`
		TueStop              string    `json:"TueStop"`
		WedStart             string    `json:"WedStart"`
		WedStop              string    `json:"WedStop"`
		ThuStart             string    `json:"ThuStart"`
		ThuStop              string    `json:"ThuStop"`
		FriStart             string    `json:"FriStart"`
		FriStop              string    `json:"FriStop"`
		SatStart             string    `json:"SatStart"`
		SatStop              string    `json:"SatStop"`
		SunStart             string    `json:"SunStart"`
		SunStop              string    `json:"SunStop"`
		PlugInfo             struct {
			ScriptFile string `json:"ScriptFile"`
			Arguments  string `json:"Arguments"`
			Version    string `json:"Version"`
		} `json:"PlugInfo"`
		Env struct {
			Vinasseneo4Juser      string `json:"VINASSENEO4JUSER"`
			Hostname              string `json:"HOSTNAME"`
			Vinassehomes          string `json:"VINASSEHOMES"`
			Vinassesiteid         string `json:"VINASSESITEID"`
			Appslocal             string `json:"APPSLOCAL"`
			SentryVentoux         string `json:"SENTRY_VENTOUX"`
			Space                 string `json:"SPACE"`
			Vinasserepos          string `json:"VINASSEREPOS"`
			Home                  string `json:"HOME"`
			Vinassetmp            string `json:"VINASSETMP"`
			Vinassehomevar        string `json:"VINASSEHOMEVAR"`
			SentryExec            string `json:"SENTRY_EXEC"`
			Vinassesitelogo       string `json:"VINASSESITELOGO"`
			Vinasseneo4Jpwd       string `json:"VINASSENEO4JPWD"`
			Sentry                string `json:"SENTRY"`
			Vinasseproject        string `json:"VINASSEPROJECT"`
			Pythonpath            string `json:"PYTHONPATH"`
			VinasseprojectsServer string `json:"VINASSEPROJECTS_SERVER"`
			User                  string `json:"USER"`
			Neo4Jservers          string `json:"NEO4JSERVERS"`
			Vinasseneo4Jport      string `json:"VINASSENEO4JPORT"`
			Vinasseprojects       string `json:"VINASSEPROJECTS"`
			Resources             string `json:"RESOURCES"`
			Vinasselog            string `json:"VINASSELOG"`
			Argsseparator         string `json:"ARGSSEPARATOR"`
			Apps                  string `json:"APPS"`
			SentryControllers     string `json:"SENTRY_CONTROLLERS"`
			EcoEnv                string `json:"ECO_ENV"`
			Vinassenfs            string `json:"VINASSENFS"`
			Vinasselocal          string `json:"VINASSELOCAL"`
			VinassehomevarServer  string `json:"VINASSEHOMEVAR_SERVER"`
			Tmp                   string `json:"TMP"`
			Path                  string `json:"PATH"`
			OcioConfigs           string `json:"OCIO_CONFIGS"`
			Vinasseneo4Jsrv       string `json:"VINASSENEO4JSRV"`
			Vinassesitename       string `json:"VINASSESITENAME"`
			SentryProtocol        string `json:"SENTRY_PROTOCOL"`
			SentryVinasse         string `json:"SENTRY_VINASSE"`
			Custompath            string `json:"CUSTOMPATH"`
			Vinasse               string `json:"VINASSE"`
			Servername            string `json:"SERVERNAME"`
			VinassePrivatekey     string `json:"VINASSE_PRIVATEKEY"`
		} `json:"Env"`
		EnvOnly  bool   `json:"EnvOnly"`
		PlugDir  string `json:"PlugDir"`
		EventDir string `json:"EventDir"`
		OptIns   struct {
		} `json:"OptIns"`
		EventOI                     []any  `json:"EventOI"`
		AWSPortalAssets             []any  `json:"AWSPortalAssets"`
		AWSPortalAssetFileWhitelist []any  `json:"AWSPortalAssetFileWhitelist"`
		Ex0                         string `json:"Ex0"`
		Ex1                         string `json:"Ex1"`
		Ex2                         string `json:"Ex2"`
		Ex3                         string `json:"Ex3"`
		Ex4                         string `json:"Ex4"`
		Ex5                         string `json:"Ex5"`
		Ex6                         string `json:"Ex6"`
		Ex7                         string `json:"Ex7"`
		Ex8                         string `json:"Ex8"`
		Ex9                         string `json:"Ex9"`
		ExDic                       struct {
		} `json:"ExDic"`
		OvrTaskEINames bool   `json:"OvrTaskEINames"`
		TaskEx0        string `json:"TaskEx0"`
		TaskEx1        string `json:"TaskEx1"`
		TaskEx2        string `json:"TaskEx2"`
		TaskEx3        string `json:"TaskEx3"`
		TaskEx4        string `json:"TaskEx4"`
		TaskEx5        string `json:"TaskEx5"`
		TaskEx6        string `json:"TaskEx6"`
		TaskEx7        string `json:"TaskEx7"`
		TaskEx8        string `json:"TaskEx8"`
		TaskEx9        string `json:"TaskEx9"`
	} `json:"Props"`
	ComFra           int       `json:"ComFra"`
	IsSub            bool      `json:"IsSub"`
	Purged           bool      `json:"Purged"`
	Mach             string    `json:"Mach"`
	Date             time.Time `json:"Date"`
	DateStart        time.Time `json:"DateStart"`
	DateComp         time.Time `json:"DateComp"`
	Plug             string    `json:"Plug"`
	OutDir           []any     `json:"OutDir"`
	OutFile          []any     `json:"OutFile"`
	TileFile         []any     `json:"TileFile"`
	Main             bool      `json:"Main"`
	MainStart        int       `json:"MainStart"`
	MainEnd          int       `json:"MainEnd"`
	Tile             bool      `json:"Tile"`
	TileFrame        int       `json:"TileFrame"`
	TileCount        int       `json:"TileCount"`
	TileX            int       `json:"TileX"`
	TileY            int       `json:"TileY"`
	Stat             int       `json:"Stat"`
	Aux              []any     `json:"Aux"`
	Bad              []any     `json:"Bad"`
	CompletedChunks  int       `json:"CompletedChunks"`
	QueuedChunks     int       `json:"QueuedChunks"`
	SuspendedChunks  int       `json:"SuspendedChunks"`
	RenderingChunks  int       `json:"RenderingChunks"`
	FailedChunks     int       `json:"FailedChunks"`
	PendingChunks    int       `json:"PendingChunks"`
	SnglTskPrg       string    `json:"SnglTskPrg"`
	Errs             int       `json:"Errs"`
	DataSize         int       `json:"DataSize"`
	ConcurrencyToken any       `json:"ConcurrencyToken"`
	ID               string    `json:"_id"`
	ExtraElements    any       `json:"ExtraElements"`
}
